<a href="https://colab.research.google.com/github/jamshid719/ai_foundation/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy


In [3]:
import numpy as np

arr = np.array([1,3,5,7])
print('numpy_array:', arr)


numpy_array: [1 3 5 7]


In [6]:
arr2 = np.array([[1, 3, 5, 7], [4, 6, 8, 9]])
print('numpy_array2:', arr2)


arr2.shape #arr shape

numpy_array2: [[1 3 5 7]
 [4 6 8 9]]


(2, 4)

In [7]:
# dtype()
a = np.array([1, 2, 3])
print(a.dtype)

int64


In [8]:
# reshape() - arr. shapeni uzgartirish
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print("shaped_array:", b)

shaped_array: [[1 2 3]
 [4 5 6]]


In [9]:
# astype() - arr. ni type ni uzgartirish
a = np.array([1, 2, 3])
b = a.astype(float)
print("float:", b)

float: [1. 2. 3.]


In [10]:
# np.zeros(), np.ones() - 0 va 1 dan tashkil topadigan arr yaratish => dummy data
z = np.zeros((2, 3))
o = np.ones((2, 3))

print("zeros:", z)
print("ones:", o)

zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones: [[1. 1. 1.]
 [1. 1. 1.]]


In [11]:

# ndim - deminsionni aniqlash (nechta vektorligini bilish un)
a = np.array([[1, 2], [3, 4]])
print("ndim:", a.ndim)

ndim: 2


In [13]:
# arange() - berilgan numberlar orqali arr. yaratadi "[ )" (bu test arr. yaratiw un kk)
a = np.arange(1, 6)
print("arange:", a)

arange: [1 2 3 4 5]


In [14]:
# sum(), mean(), max(), min()
a = np.array([1, 2, 3, 4])

print("sum:", a.sum())
print("mean:", a.mean())
print("max:", a.max())
print("min:", a.min())

sum: 10
mean: 2.5
max: 4
min: 1


In [15]:
# flatten() - 2d, 3d arr.larni 1d arr. list ga aylantiradi(rasmlar bn ishlashda qullaniladi)
a = np.array([[1, 2], [3, 4]])
print("flatten:", a.flatten())

flatten: [1 2 3 4]


In [16]:
# T (Transpose) method - bu arr.lar ichidagi num.larni random sifatida almashtiradi yoki
a = np.array([[1, 2], [3, 4]])
print("transpose:", a.T)

transpose: [[1 3]
 [2 4]]


In [18]:
# dot() @ - Matrix multiplication da a ning qatori bilan b ning ustuni kupaytirilib qushiladi.
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 2]])
print("dot/multiplication:", a.dot(b))

dot/multiplication: [[ 4  4]
 [10  8]]


In [17]:
# random.rand() - 0 va 1 oraligida random arr.lar yaratadi.
a = np.random.rand(2, 3)  # => 0.0 and 1.0 / 0.0 included / 1.0 excluded
print("random rand:", a)

random rand: [[0.07189241 0.29416637 0.64211584]
 [0.6706597  0.90974748 0.75210838]]
